[data]
files_prefix = "data/2025/08/10/"
files = [
    "zantiks_a/sleep-20250810T075451.csv",
    "zantiks_b/sleep-20250810T075515.csv",
]
assay_names = [
    "sleep",
    "sleep",
]
wildtype_file = "configs/wildtype/sleep.toml"

[genotypes]
files_prefix = "data/2025/08/10/genotypes.csv"
files = [
    "",
    "",
]
counting_directions = [
    "down",
    "down",
]

[fish_used]
files_prefix = "templates/fish_used/"
files = [
    "zantiks_left.txt",
    "zantiks_right.txt",
]

[output]
file = ""
